### ISSUE TITLE
babel/babel-sublime

### ISSUE THREAD

**Issue by sospedra** [sospedra/rfm#31]
{
    "description": "Syntax definitions for ES6 JavaScript with React JSX extensions.",
    "fullName": "babel/babel-sublime",
    "language": "JavaScript",
    "name": "babel-sublime",
    "openIssues": 22,
    "owner": "babel",
    "stars": 3200,
    "updatedAt": "2020-04-20T09:11:44Z",
    "url": "https://github.com/babel/babel-sublime",
    "license": "MIT",
    "topics": [],
    "filenames": [
        "Jakefile"
    ],
    "aceMode": "javascript",
    "aliases": [
        "js",
        "node"
    ],
    "color": "#f1e05a",
    "extensions": [
        ".js",
        "._js",
        ".bones",
        ".es",
        ".es6",
        ".frag",
        ".gs",
        ".jake",
        ".jsb",
        ".jscad",
        ".jsfl",
        ".jsm",
        ".jss",
        ".mjs",
        ".njs",
        ".pac",
        ".sjs",
        ".ssjs",
        ".xsjs",
        ".xsjslib"
    ],
    "interpreters": [
        "node"
    ]
}

**Comment by Thom1729** [comment]
Yes, the repo is maintained.

**Comment by sospedra** [comment]
> Yes, the repo is maintained.

Thank you. I marked it as resolved ;)
Good luck with the project 🖖
