### ISSUE TITLE
JuliaMath/SpecialFunctions.jl

### ISSUE THREAD

**Issue by sospedra** [sospedra/rfm#32]
{
    "description": "Special mathematical functions in Julia",
    "fullName": "JuliaMath/SpecialFunctions.jl",
    "language": "Julia",
    "name": "SpecialFunctions.jl",
    "openIssues": 41,
    "owner": "JuliaMath",
    "stars": 98,
    "updatedAt": "2020-04-14T12:54:51Z",
    "url": "https://github.com/JuliaMath/SpecialFunctions.jl",
    "license": "NOASSERTION",
    "topics": [
        "julia",
        "math",
        "special-functions"
    ],
    "aceMode": "julia",
    "color": "#a270ba",
    "extensions": [
        ".jl"
    ],
    "interpreters": [
        "julia"
    ]
}

**Comment by ararslan** [comment]
SpecialFunctions is fine?

**Comment by sospedra** [comment]
> SpecialFunctions is fine?

It's a question? If the repo doesn't need any support I'll close the issue 😇

**Comment by ararslan** [comment]
The question mark was because I'm confused by this issue. That package is very specialized, so while it could do with helping hands (as could many open source projects), it requires a very specific kind of background to be able to review changes effectively. I think this issue could be safely closed, as options for collaborators are being discussed by the community.

**Comment by sospedra** [comment]
> The question mark was because I'm confused by this issue. That package is very specialized, so while it could do with helping hands (as could many open source projects), it requires a very specific kind of background to be able to review changes effectively. I think this issue could be safely closed, as options for collaborators are being discussed by the community.

Thanks for the clarification
I'll close it per your request 😇🖖

**Comment by sospedra** [comment]
> The question mark was because I'm confused by this issue. That package is very specialized, so while it could do with helping hands (as could many open source projects), it requires a very specific kind of background to be able to review changes effectively. I think this issue could be safely closed, as options for collaborators are being discussed by the community.

Thanks for the clarification
I'll close it per your request 😇🖖
