### ISSUE TITLE
uuvsimulator/uuv_simulator

### ISSUE THREAD

**Issue by sospedra** [sospedra/rfm#44]
{
    "description": "Gazebo/ROS packages for underwater robotics simulation",
    "fullName": "uuvsimulator/uuv_simulator",
    "language": "Python",
    "name": "uuv_simulator",
    "openIssues": 76,
    "owner": "uuvsimulator",
    "stars": 228,
    "updatedAt": "2020-04-17T02:37:15Z",
    "url": "https://github.com/uuvsimulator/uuv_simulator",
    "license": "NOASSERTION",
    "topics": [
        "auv",
        "gazebo",
        "robotics-simulation",
        "ros",
        "rov",
        "simulation",
        "swarms-project",
        "underwater",
        "uuv"
    ],
    "filenames": [
        ".gclient",
        "BUCK",
        "BUILD",
        "BUILD.bazel",
        "SConscript",
        "SConstruct",
        "Snakefile",
        "WORKSPACE",
        "wscript"
    ],
    "aceMode": "python",
    "aliases": [
        "rusthon",
        "python3"
    ],
    "color": "#3572A5",
    "extensions": [
        ".py",
        ".bzl",
        ".cgi",
        ".fcgi",
        ".gyp",
        ".gypi",
        ".lmi",
        ".py3",
        ".pyde",
        ".pyi",
        ".pyp",
        ".pyt",
        ".pyw",
        ".rpy",
        ".spec",
        ".tac",
        ".wsgi",
        ".xpy"
    ],
    "interpreters": [
        "python",
        "python2",
        "python3"
    ]
}

**Comment by musamarcusso** [comment]
we were in the process of obtaining more maintainers, they were now included in the project.

**Comment by sospedra** [comment]
> we were in the process of obtaining more maintainers, they were now included in the project.

You're not looking for more collaborators then? I can close the issue if so ;)

**Comment by musamarcusso** [comment]
yes, you can close it :) unfortunately since the repository was created within the scope of my company's project, getting collaborators involves some paperwork
