### ISSUE TITLE
meedan/react-native-share-menu

### ISSUE THREAD

**Issue by durdevic** [sospedra/rfm#55]
{
    "description": "A module for React Native that adds your app to the share menu of the device",
    "fullName": "meedan/react-native-share-menu",
    "language": "Objective-C",
    "name": "react-native-share-menu",
    "openIssues": 9,
    "owner": "meedan",
    "stars": 146,
    "updatedAt": "2020-04-14T19:31:11Z",
    "url": "https://github.com/meedan/react-native-share-menu",
    "requestIssueFullName": "meedan/react-native-share-menu",
    "requestIssueNumber": 27,
    "license": "MIT",
    "topics": [
        "react-native",
        "share-intent"
    ],
    "aceMode": "objectivec",
    "aliases": [
        "obj-c",
        "objc",
        "objectivec"
    ],
    "color": "#438eff",
    "extensions": [
        ".m",
        ".h"
    ]
}

**Comment by sospedra** [comment]
The good people at there finally found a maintainer :)

**Comment by durdevic** [comment]
> The good people at there finally found a maintainer :)

Yeah, all thanks to you! Awesome job guys! 😊
