### ISSUE TITLE
rgbkrk/atom-script

### ISSUE THREAD

**Issue by sospedra** [sospedra/rfm#57]
{
    "description": ":runner: Run ( scripts | selections | source ) in Atom",
    "fullName": "rgbkrk/atom-script",
    "language": "JavaScript",
    "name": "atom-script",
    "openIssues": 1091,
    "owner": "rgbkrk",
    "stars": 667,
    "updatedAt": "2020-05-02T00:34:04Z",
    "url": "https://github.com/rgbkrk/atom-script",
    "requestIssueFullName": "rgbkrk/atom-script",
    "requestIssueNumber": 1550,
    "license": "MIT",
    "topics": [],
    "filenames": [
        "Jakefile"
    ],
    "aceMode": "javascript",
    "aliases": [
        "js",
        "node"
    ],
    "color": "#f1e05a",
    "extensions": [
        ".js",
        "._js",
        ".bones",
        ".es",
        ".es6",
        ".frag",
        ".gs",
        ".jake",
        ".jsb",
        ".jscad",
        ".jsfl",
        ".jsm",
        ".jss",
        ".mjs",
        ".njs",
        ".pac",
        ".sjs",
        ".ssjs",
        ".xsjs",
        ".xsjslib"
    ],
    "interpreters": [
        "node"
    ]
}

**Comment by AlexThundrous** [comment]
It's well supported please close the repo

**Comment by kadirselcuk** [comment]
Is the atom script supported here
