### ISSUE TITLE
tortoise/tortoise-orm

### ISSUE THREAD

**Issue by sospedra** [sospedra/rfm#72]
{
    "description": "Familiar asyncio ORM for python, built with relations in mind",
    "fullName": "tortoise/tortoise-orm",
    "language": "Python",
    "name": "tortoise-orm",
    "openIssues": 107,
    "owner": "tortoise",
    "stars": 1260,
    "updatedAt": "2020-09-01T03:01:12Z",
    "url": "https://github.com/tortoise/tortoise-orm",
    "requestIssueFullName": "tortoise/tortoise-orm",
    "requestIssueNumber": 488,
    "license": "Apache-2.0",
    "topics": [
        "async",
        "asyncio",
        "mysql",
        "orm",
        "postgresql",
        "python3",
        "sqlite"
    ],
    "filenames": [
        ".gclient",
        "BUCK",
        "BUILD",
        "BUILD.bazel",
        "SConscript",
        "SConstruct",
        "Snakefile",
        "WORKSPACE",
        "wscript"
    ],
    "aceMode": "python",
    "aliases": [
        "rusthon",
        "python3"
    ],
    "color": "#3572A5",
    "extensions": [
        ".py",
        ".bzl",
        ".cgi",
        ".fcgi",
        ".gyp",
        ".gypi",
        ".lmi",
        ".py3",
        ".pyde",
        ".pyi",
        ".pyp",
        ".pyt",
        ".pyw",
        ".rpy",
        ".spec",
        ".tac",
        ".wsgi",
        ".xpy"
    ],
    "interpreters": [
        "python",
        "python2",
        "python3"
    ]
}

**Comment by grigi** [comment]
It was a call for **MORE** maintainers, not that there is no maintenance done on it.
And it was somewhat successful, we got a regular contributor to take on the maintenance mantle :smile: 

I'm going to delete the message, as, yup, it's a bit spammy.
You can also close this issue. Thank you for checking up with us :smile:

**Comment by sospedra** [comment]
Sure! Ty for the feedback 😊
